maps = {'0707937f153ccc5d': {'name': 'Kursk',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        '000000c0f0ffffff': {'name': 'Second_Battle_of_El_Alamein',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        '000820e066cf9fff': {'name': 'Frozen_Pass',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        '00016000f3ffffb6': {'name': 'Berlin',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        '080503071f1f0f8f': {'name': 'Ruhr_Large',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        '080502071f1f0f8f': {'name': 'Ruhr_Small',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        'fffff9f8d8c0c000': {'name': 'Wake_Island',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        'f7fef9f8d8c08000': {'name': 'Wake_Island',
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
}