maps = {'0707937f153ccc5d': {'name': 'Kursk_Large',
                             'grids_x': 8,
                             'grids_y': 8,
                             'grid_width_km': 8,
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        '00c0f0f898f8f8f0': {'name': 'Kursk_Small',
                             'grids_x': 10,
                             'grids_y': 10,
                             'grid_width_km': 8,
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        '000000c0f0ffffff': {'name': 'Second_Battle_of_El_Alamein',
                             'grids_x': 10,
                             'grids_y': 10,
                             'grid_width_km': 6.5,
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        '000820e066cf9fff': {'name': 'Frozen_Pass',
                             'grids_x': 17,
                             'grids_y': 17,
                             'grid_width_km': 4,
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        '00016000f3ffffb6': {'name': 'Berlin',
                             'grids_x': 10,
                             'grids_y': 10,
                             'grid_width_km': 6.5,
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        '5f0f0710188088ff': {'name': 'Berlin_1945',
                             'grids_x': 8,
                             'grids_y': 8,
                             'grid_width_km': 8,
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        '080503071f1f0f8f': {'name': 'Ruhr_Large',
                             'grids_x': 8,
                             'grids_y': 8,
                             'grid_width_km': 8,
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0},
        '080502071f1f0f8f': {'name': 'Ruhr_Small',
                             'grids_x': 8,
                             'grids_y': 8,
                             'grid_width_km': 8,
                             'ULHC_lat': 0.0,
                             'ULHC_lon': 0.0}
}